# Generated by Django 5.0 on 2024-01-01 07:43

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('exp_date', models.DateField(verbose_name='expiry date')),
                ('cvc_code', models.CharField(max_length=3, verbose_name='security code')),
                ('owner_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CATG', 'Category'), ('MCHT', 'Merchant'), ('MXAM', 'Max Amount'), ('MNAM', 'Min Amount')], default='CATG', max_length=4)),
                ('value', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='creation timestamp')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('APPR', 'Approved'), ('DEC', 'Declined')], max_length=4)),
                ('message', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('number',), name='unique_card'),
        ),
        migrations.AddField(
            model_name='cardcontrol',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
        migrations.AddConstraint(
            model_name='cardcontrol',
            constraint=models.UniqueConstraint(fields=('card', 'type', 'value'), name='unique_card_control'),
        ),
    ]
