# Generated by Django 5.0 on 2023-12-27 13:35

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('exp_date', models.DateField(verbose_name='expiry date')),
                ('cvc_code', models.CharField(max_length=3, verbose_name='security code')),
                ('owner_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CATG', 'Category'), ('MCHT', 'Merchent'), ('MXAM', 'Max Amount'), ('MNAM', 'Min Amount')], default='CATG', max_length=4)),
                ('value', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='creation timestamp')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('APPR', 'Approved'), ('DEC', 'Declined')], default='APPR', max_length=4)),
                ('message', models.CharField(default='', max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
    ]
