# Generated by Django 5.0 on 2024-01-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcontrol',
            name='type',
            field=models.CharField(choices=[('CATG', 'Category'), ('MCHT', 'Merchant'), ('MXAM', 'Max Amount'), ('MNAM', 'Min Amount')], default='CATG', max_length=4),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('APPR', 'Approved'), ('DEC', 'Declined')], max_length=4),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('number',), name='unique_card'),
        ),
        migrations.AddConstraint(
            model_name='cardcontrol',
            constraint=models.UniqueConstraint(fields=('card', 'type', 'value'), name='unique_card_control'),
        ),
    ]
