# Generated by Django 5.0 on 2024-01-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_cardcontrol_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
